### ISSUE TITLE
PlayRandom repeats vids

### ISSUE THREAD

**Issue by justinwash** [Trifectuh/PerpetualShred#5]
PlayRandom should only play each video once until it runs out of things to play.

**Comment by nwash57** [comment]
I solved this with commit 0be8943460984126917575d9bde5be1f3bed2161 by creating a cookie service (CookieService.cs) and using it to create a cookie that has the id for each video that has NOT been played by the user yet. Upon loading the random video page again it removes the id of the video that the randomizer chooses so that it cannot be chosen again. If the cookie is empty or doesn't exist then it is repopulated with the full video list again.
